version: '2'
services:
  web:
    image: mhart/alpine-node
    ports:
      - 81:81
    working_dir: /app
    command: npm run start
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
    driver: local
